"""
Global_Training_FIXED.py  —  corrected global training
=========================================================================
Fixes relative to the original `Global Training.py` (see the matching IDs):

[Leak-3] Splitting: the original train_test_split(file_paths) put different load sets of the "same subject"
         into both train and val, so val consisted only of people already seen → not cross-subject.
         This version uses a per-subject GroupShuffleSplit and provides a LOSO evaluation function.
[Leak-1] Removed Load_1RM_Ratio: it no longer enters ts_cols or static_cols (unknown at deployment).
[Eval-8] Added per-muscle Pearson r, reported on a "subject-disjoint" val set.
[Feature-10] v/a is switched by FEATURE_MODE instead of being silently dropped by exclude.
[Leak-4] Compensation classification **was completely removed on 2026-08-04** (the labels were hard thresholds on input features, i.e. circular reasoning).
         This model is single-task and predicts only %MVC; compensation is now derived afterwards from the predicted EMG.
         See the "multi-task removed" block below.

Note: the scaler is fit on train only (keeping the original code's correct practice).
"""
# --- Paths: always managed centrally by paths.py at the repo root; do not revert to absolute paths ---
import os as _os, sys as _sys
_sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))
from paths import (  # noqa: E402,F401
    REPO_ROOT, PIPELINE_DIR, EXPERIMENTS_DIR, RESULTS_DIR,
    DATASET_DIR, RAW_DIR, CLEAN_DIR, CLEAN_60FPS_DIR, CLEAN_1000HZ_DIR,
    COMBINED_DIR, COMBINED_BEFORE_AXISFIX_DIR, OPEN_DIR, SKELETON_DIR,
    GLOBAL_MODEL_DIR, LOSO_MODEL_DIR,
    PERSONALIZED_FROM_LOSO_DIR, PERSONALIZED_NONTWO_DIR, PERSONALIZED_FROM_GLOBAL_DIR,
    ABL_BEFORE_AXISFIX_DIR, ABL_MASKED_DIR, ABL_EXCLUDE_S09_DIR, ABL_HOLDOUT_TWO_DIR,
    SUBJECTS_CSV, SUBJECTS_EXAMPLE_CSV,
    ensure_results_dir, require_dataset, require_subjects_csv,
)
# --- End of path setup ---


import os
import glob
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import (Input, Dense, Dropout, Conv1D,
                                     BatchNormalization, GlobalAveragePooling1D,
                                     Concatenate)
from sklearn.model_selection import GroupShuffleSplit, LeaveOneGroupOut
from sklearn.preprocessing import StandardScaler
import joblib

from eval_utils import (subject_id_from_path, build_ts_cols,
                        pearson_per_column, make_windows, add_comp_labels)

# ==========================================
# 0. settings
# ==========================================
DATA_DIR = COMBINED_DIR
FEATURE_MODE = "spatial"        # "spatial" or "spatial+kinematic"
RUN_LOSO = True                 # additionally run an honest Leave-One-Subject-Out generalization evaluation
WINDOW_SIZE = 40
STEP_SIZE = 5
RANDOM_STATE = 42

STATIC_COLS = ['Subj_Age', 'Subj_Height_m', 'Subj_Weight_norm', 'Subj_Gender']  # ★ Load_1RM_Ratio removed
LABEL_EMG_COLS = ['EMG_Main_MVC', 'EMG_Compass_MVC']

# ==========================================
# ⛔ multi-task (compensation classification) was removed on 2026-08-04
# ==========================================
# This model is **single-task**: it only predicts the %MVC EMG signal.
#
# Reasons for removal (both are fatal flaws):
#   1. `Comp_Knee_Valgus` is a rule-based pseudo-label **computed from the input features themselves** via `Knee_Ankle_Ratio_norm < 0.758`
#      — i.e. making the model learn a rule determined by its own inputs, which is circular reasoning.
#   2. The “dynamically weighted joint loss” was actually just a fixed `loss_w['out_comp'] = 1.0`,
#      which does not match the description in the literature.
#
# Compensation detection is now **derived afterwards from the predicted EMG**, which is also closer to the original intent of step 3.4 of the NSTC proposal:
#   “the virtual EMG generated by the model will show abnormal erector spinae activation and insufficient quadriceps activation, allowing compensation to be identified precisely”
# — compensation should be read from the EMG in the first place, not from a separate classification head.
#
# `eval_utils.add_comp_labels()` / `COMP_THRESHOLDS` are kept for **post-hoc labelling and diagnostics**,
# but no longer enter any loss function.


# ==========================================
# 1. read files
# ==========================================
def load_one(fp):
    df = pd.read_csv(fp)
    # compensation labels are for post-hoc diagnostics only and do not enter training.
    # ★ thresholds are centralized in eval_utils.COMP_THRESHOLDS; do not hard-code them here (see the history lesson in the comment there)
    return add_comp_labels(df)


def build_model(n_ts_feat, n_static):
    """Conv1D×2 + GAP → fused with static features → 2 %MVC outputs (single task)."""
    input_ts = Input(shape=(WINDOW_SIZE, n_ts_feat), name='ts_input')
    input_static = Input(shape=(n_static,), name='static_input')

    x = Conv1D(64, 3, padding='causal', activation='relu', name='feature_conv1')(input_ts)
    x = BatchNormalization(name='feature_bn1')(x)
    x = Conv1D(64, 3, padding='causal', dilation_rate=2, activation='relu', name='feature_conv2')(x)
    ts_feat = GlobalAveragePooling1D(name='feature_pool')(x)

    fused = Concatenate(name='fusion_concat')([ts_feat, input_static])
    fused = Dense(64, activation='relu', name='fusion_dense')(fused)
    fused = Dropout(0.2, name='fusion_dropout')(fused)

    emg_branch = Dense(32, activation='relu', name='emg_dense')(fused)
    # sigmoid keeps the output in [0,1] (the physiological %MVC range), more sensible than the original linear
    out_emg = Dense(2, activation='sigmoid', name='out_emg')(emg_branch)

    model = tf.keras.Model(inputs=[input_ts, input_static], outputs=[out_emg])
    model.compile(optimizer=tf.keras.optimizers.Adam(1e-3),
                  loss={'out_emg': 'mse'}, loss_weights={'out_emg': 3.0},
                  metrics={'out_emg': 'mae'})
    return model


def fit_scalers(train_dfs, ts_cols):
    big = pd.concat(train_dfs, ignore_index=True)
    s_ts = StandardScaler().fit(big[ts_cols].values)
    s_st = StandardScaler().fit(big[STATIC_COLS].values)
    return s_ts, s_st


def evaluate_pearson(model, dfs, ts_cols, s_ts, s_st, tag=""):
    Xts, Xst, Yemg, _ = make_windows(
        dfs, ts_cols, STATIC_COLS, LABEL_EMG_COLS,
        label_comp_cols=None, window_size=WINDOW_SIZE, step_size=STEP_SIZE,
        scaler_ts=s_ts, scaler_static=s_st)
    if len(Xts) == 0:
        print(f"  [{tag}] not enough samples"); return None
    pred = model.predict({'ts_input': Xts, 'static_input': Xst}, verbose=0)
    pred_emg = pred[0] if isinstance(pred, list) else pred
    r = pearson_per_column(Yemg, pred_emg)
    mae = np.mean(np.abs(Yemg - pred_emg), axis=0)
    print(f"  [{tag}] Pearson r  main={r[0]:.3f}  synergist={r[1]:.3f} | "
          f"MAE main={mae[0]:.3f} synergist={mae[1]:.3f}")
    return r


# ==========================================
# 2. main flow
# ==========================================
def main():
    file_paths = sorted(glob.glob(os.path.join(DATA_DIR, "*_Combined_Features.csv")))
    if not file_paths:
        raise FileNotFoundError(f"no *_Combined_Features.csv found in {DATA_DIR}")

    groups = [subject_id_from_path(p) for p in file_paths]
    subjects = sorted(set(groups))
    print(f"📂 files={len(file_paths)}  subjects={len(subjects)}  -> {subjects}")

    if len(subjects) < 2:
        print("⚠️ Only 1 subject: cannot do a cross-subject split.")
        print("   Only “personalized” experiments are possible for now; generalization conclusions do not hold. Please add data from more subjects first.")

    # determine ts_cols (using the first file's columns as the template)
    sample_cols = load_one(file_paths[0]).columns.tolist()
    ts_cols = build_ts_cols(sample_cols, FEATURE_MODE)
    print(f"🧩 FEATURE_MODE={FEATURE_MODE} | time-series features={len(ts_cols)} | single task (EMG only)")

    # ---------- main training: split train/val by subject ----------
    if len(subjects) >= 2:
        gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=RANDOM_STATE)
        tr_idx, va_idx = next(gss.split(file_paths, groups=groups))
    else:
        # single-subject fallback: split by file (only so the program runs; not cross-subject)
        tr_idx = list(range(len(file_paths)))[:-1]
        va_idx = list(range(len(file_paths)))[-1:]

    train_files = [file_paths[i] for i in tr_idx]
    val_files = [file_paths[i] for i in va_idx]
    train_subj = set(subject_id_from_path(p) for p in train_files)
    val_subj = set(subject_id_from_path(p) for p in val_files)
    assert train_subj.isdisjoint(val_subj) or len(subjects) < 2, \
        "Subject leakage: train and val share subjects!"
    print(f"   train subjects={sorted(train_subj)}  val subjects={sorted(val_subj)}")

    train_dfs = [load_one(p) for p in train_files]
    val_dfs = [load_one(p) for p in val_files]

    s_ts, s_st = fit_scalers(train_dfs, ts_cols)   # ★ fit on train only
    joblib.dump(s_ts, os.path.join(GLOBAL_MODEL_DIR, 'global_scaler_ts.pkl'))
    joblib.dump(s_st, os.path.join(GLOBAL_MODEL_DIR, 'global_scaler_static.pkl'))
    # record the ts_cols order for alignment in phase2
    joblib.dump({'ts_cols': ts_cols, 'static_cols': STATIC_COLS,
                 'feature_mode': FEATURE_MODE},
                os.path.join(GLOBAL_MODEL_DIR, 'global_feature_spec.pkl'))

    comp_cols = None          # single task: compensation label tensors are no longer produced
    Xtr_ts, Xtr_st, Ytr_emg, Ytr_comp = make_windows(
        train_dfs, ts_cols, STATIC_COLS, LABEL_EMG_COLS, comp_cols,
        WINDOW_SIZE, STEP_SIZE, s_ts, s_st)
    Xva_ts, Xva_st, Yva_emg, Yva_comp = make_windows(
        val_dfs, ts_cols, STATIC_COLS, LABEL_EMG_COLS, comp_cols,
        WINDOW_SIZE, STEP_SIZE, s_ts, s_st)
    print(f"   train windows={len(Xtr_ts)}  val windows={len(Xva_ts)}")

    model = build_model(len(ts_cols), len(STATIC_COLS))

    y_tr = {'out_emg': Ytr_emg}
    y_va = {'out_emg': Yva_emg}

    cbs = [
        tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=10,
                                         restore_best_weights=True),
        tf.keras.callbacks.ModelCheckpoint(os.path.join(GLOBAL_MODEL_DIR, 'global_fitness_model_best.keras'),
                                           monitor='val_loss', save_best_only=True,
                                           mode='min', verbose=1),
    ]
    model.fit({'ts_input': Xtr_ts, 'static_input': Xtr_st}, y_tr,
              epochs=50, batch_size=32,
              validation_data=({'ts_input': Xva_ts, 'static_input': Xva_st}, y_va),
              callbacks=cbs, verbose=1)
    model.save(os.path.join(GLOBAL_MODEL_DIR, 'global_fitness_model.keras'))
    print("\n✅ Global model saved to global_fitness_model.keras")

    print("\n📊 Cross-subject validation (subject-disjoint):")
    evaluate_pearson(model, val_dfs, ts_cols, s_ts, s_st, tag="Val/Unseen-Subject")

    # ---------- optional: honest LOSO generalization evaluation ----------
    if RUN_LOSO and len(subjects) >= 2:
        print("\n" + "=" * 60)
        print("🔁 Leave-One-Subject-Out evaluation (the correct approach for the paper's Experiment A)")
        print("=" * 60)
        logo = LeaveOneGroupOut()
        all_r = []
        for tr_i, va_i in logo.split(file_paths, groups=groups):
            hold = subject_id_from_path(file_paths[va_i[0]])
            tr_dfs = [load_one(file_paths[i]) for i in tr_i]
            va_dfs = [load_one(file_paths[i]) for i in va_i]
            sts, sst = fit_scalers(tr_dfs, ts_cols)
            xt, xs, ye, yc = make_windows(tr_dfs, ts_cols, STATIC_COLS,
                                          LABEL_EMG_COLS, comp_cols,
                                          WINDOW_SIZE, STEP_SIZE, sts, sst)
            m = build_model(len(ts_cols), len(STATIC_COLS))
            yy = {'out_emg': ye}
            m.fit({'ts_input': xt, 'static_input': xs}, yy,
                  epochs=30, batch_size=32, verbose=0)
            r = evaluate_pearson(m, va_dfs, ts_cols, sts, sst, tag=f"LOSO holdout={hold}")
            if r is not None:
                all_r.append(r)
        if all_r:
            all_r = np.array(all_r)
            print(f"\n📈 LOSO mean Pearson r: main={np.nanmean(all_r[:,0]):.3f} "
                  f"synergist={np.nanmean(all_r[:,1]):.3f}")
            print("   (this is the “zero-shot cross-subject” number that can go into the paper)")


if __name__ == '__main__':
    main()
